Repository OpossumTS/opossumts-wiki, pull requests merged in 2019-10, with the labels that each got.

#1 Umformulieren, kürzungen und Danger Boxen, desc.
  de/bots-und-automatisierung/ranking-and-activity.md
Labels: enhancement

#2 How about a list of custom tags used?
  README.md
Labels: documentation, enhancement

#4 Rechtschreibfehler behoben
  de/rules/code-of-conduct.md
Labels: enhancement

#5 Rechtschreibung und Grammatik
  de/rules/code-of-conduct.md
Labels: enhancement, typo
